name = "CbrnAlertApp"
uuid = "a24d0d5a-6e7e-4c07-92eb-499b57f1510c"
authors = ["tcarion <tristancarion@gmail.com>"]
version = "0.1.0"

[deps]
ATP45 = "e618d77b-d0d4-44a4-84cd-7e2c5c764d14"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
EcRequests = "c0c4b1a4-92fd-414d-990e-850c1287bada"
Flexpart = "fb362612-c2d8-4302-a9fd-a07f2890630f"
GRIB = "b16dfd50-4035-11e9-28d4-9dfe17e6779b"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONWebTokens = "9b8beb19-0777-58c6-920b-28f749fee4d3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDFF_jll = "78e728a9-57fe-5d11-897c-5014b89e5f84"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightSQLite = "21a827c4-482a-11ea-3a19-4d2243a4a2c5"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SwagUI = "bf05d729-34b2-4f1f-a2f1-2452bece7ebc"
SwaggerMarkdown = "1b6eb727-ad4b-44eb-9669-b9596a6e760f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia="1.7"
NetCDFF_jll="4.5.3"